name: fd_tracker
description: A Flutter app for tracking Fixed Deposits (FDs).
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.20.2
  provider: ^6.1.5+1
  fl_chart: ^0.64.0
  lottie: ^3.3.1
  shared_preferences: ^2.3.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/