name: my_notes
description: Offline Notes App using SQLite
publish_to: 'none'
version: 1.0.0+1

environment:
 sdk: ">=2.17.0 <4.0.0"

dependencies:
 flutter:
  sdk: flutter
 sqflite: ^2.3.0
 path_provider: ^2.1.1

flutter:
 uses-material-design: true
